version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: reachinbox-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
